"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

type AnalyzeResponse = {
  analysis?: string;
  error?: string;
};

export function CvAnalyzer() {
  const [cv, setCv] = useState("");
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleAnalyze() {
    setLoading(true);
    setError(null);
    setAnalysis(null);

    try {
      const res = await fetch("/api/analyze-cv", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cv }),
      });

      const data = (await res.json()) as AnalyzeResponse;

      if (!res.ok) {
        setError(data.error ?? `Request failed with status ${res.status}`);
        return;
      }

      setAnalysis(data.analysis ?? "");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unexpected error");
    } finally {
      setLoading(false);
    }
  }

  const disabled = loading || cv.trim().length < 50;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Candidate CV</CardTitle>
          <CardDescription>
            Paste the candidate&apos;s CV as plain text. Minimum 50 characters.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea
            value={cv}
            onChange={(e) => setCv(e.target.value)}
            placeholder="Paste the CV here…"
            className="min-h-[280px] font-mono text-sm"
            disabled={loading}
          />
          <div className="flex items-center justify-between text-sm text-muted-foreground">
            <span>{cv.length.toLocaleString()} characters</span>
            <Button onClick={handleAnalyze} disabled={disabled}>
              {loading ? "Analyzing…" : "Analyze with Claude"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {error && (
        <Card className="border-destructive/50 bg-destructive/5">
          <CardHeader>
            <CardTitle className="text-destructive">Error</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-destructive">{error}</p>
          </CardContent>
        </Card>
      )}

      {analysis && (
        <Card>
          <CardHeader>
            <CardTitle>Analysis</CardTitle>
            <CardDescription>Generated by Claude Sonnet 4.6.</CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="whitespace-pre-wrap text-sm leading-relaxed">
              {analysis}
            </pre>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
